#!/bin/bash
export PATH=$PATH:/home/chenzhiyong/shared/project/buildroot/output/host/bin
echo "PATH="$PATH

export ARCH=arm
echo "ARCH="$ARCH

export CROSS_COMPILE=arm-linux-
echo "CROSS_COMPILE="$CROSS_COMPILE